Copyright **`(c)`** 2025 Giovanni Squillero `<giovanni.squillero@polito.it>`  
[`https://github.com/squillero/computational-intelligence`](https://github.com/squillero/computational-intelligence)  
Free under certain conditions — see the [`license`](https://github.com/squillero/computational-intelligence/blob/master/LICENSE.md) for details.  

In [16]:
import numpy as np

## Problem Description

GOAL: maximizing the value and minimizing the weight of objects carried by the <NUM_KNAPSACKS> knapsacks

We should respect the contraints on the weight, which defines how much weights a knapsack can carry.

a dimension defines a contraint on a napsack.
Ex. [x, y, z] -> 3 constraints on backpack 1.

## Hill climbing - Techniques Used

select randomly a knapsack

2 kinds of tweaks:
- if the weights go out of the constraints don't carry the object
- if constraints are satisfied, try to add a random object. If that random object is already selected, try to add another one. Save the state only if the solution is better (hill climbing)

In [17]:
NUM_KNAPSACKS = 2
NUM_ITEMS = 10
NUM_DIMENSIONS = 2

In [18]:
VALUES = np.random.randint(0, 100, size=NUM_ITEMS)
WEIGHTS = np.random.randint(0, 100, size=(NUM_ITEMS, NUM_DIMENSIONS))
CONSTRAINTS = np.random.randint(0, 100 * NUM_ITEMS // NUM_KNAPSACKS, size=NUM_DIMENSIONS)

In [19]:
# A random solution - starting point
solution = np.array(
    [np.random.random(NUM_ITEMS) < 0.5 for _ in range(NUM_KNAPSACKS)], dtype=np.bool
)

In [20]:
solution

array([[ True,  True,  True, False, False, False, False, False, False,
        False],
       [ True, False,  True,  True,  True, False,  True,  True, False,
         True]])

In [21]:
# Check that the same object does not appear in multiple knapsacks
np.all(solution.sum(axis=0) <= 1)

np.False_

In [22]:
# Check if the solution is valid
all_knapsacks = np.any(solution, axis=0)
np.all(WEIGHTS[all_knapsacks].sum(axis=0) < CONSTRAINTS)

np.True_

## FUNCTIONS UTILS

In [23]:
# the solution already starts with 1 object that is carried exactly by 1 knapsack,
# so we will never have 1 

def gen_solution(NUM_KNAPSACKS, NUM_ITEMS):
    # A random solution - starting point
    solution = np.array(
        [np.random.random(NUM_ITEMS) < 0.5 for _ in range(NUM_KNAPSACKS)], dtype=np.int32
    )

    return solution

In [24]:
def print_info(VALUES, WEIGHTS, CONSTRAINTS):
    print(f"VALUES: {VALUES}")
    print(f"WEIGHTS: {WEIGHTS}")
    print(f"CONSTRAINTS: {CONSTRAINTS}")

In [25]:
def reset_matrix(NUM_KNAPSACKS, NUM_ITEMS):
    return np.zeros((NUM_KNAPSACKS, NUM_ITEMS), dtype = np.int8)

In [ ]:
# return TRUE if al constraints are satisfied, FALSE otherwise

def constrain_satisfied(matrix):


## TEST PROBLEMS

rng = np.random.default_rng(seed = 42)  #Random Number Generator

In [26]:
# Problem 1:
rng = np.random.default_rng(seed=42)
NUM_KNAPSACKS = 3
NUM_ITEMS = 20
NUM_DIMENSIONS = 2
VALUES = rng.integers(0, 100, size=NUM_ITEMS)
WEIGHTS = rng.integers(0, 100, size=(NUM_ITEMS, NUM_DIMENSIONS))
CONSTRAINTS = rng.integers(0, 100 * NUM_ITEMS // NUM_KNAPSACKS, size=NUM_DIMENSIONS)

print_info(VALUES, WEIGHTS, CONSTRAINTS)

VALUES: [ 8 77 65 43 43 85  8 69 20  9 52 97 73 76 71 78 51 12 83 45]
WEIGHTS: [[50 37]
 [18 92]
 [78 64]
 [40 82]
 [54 44]
 [45 22]
 [ 9 55]
 [88  6]
 [85 82]
 [27 63]
 [16 75]
 [70 35]
 [ 6 97]
 [44 89]
 [67 77]
 [75 19]
 [36 46]
 [49  4]
 [54 15]
 [74 68]]
CONSTRAINTS: [614 496]


In [27]:
starting_solution = gen_solution(NUM_KNAPSACKS, NUM_ITEMS)
print(starting_solution)

[[1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 1]
 [1 1 1 1 1 0 0 1 1 0 0 1 1 1 1 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0]]


In [28]:
# Problem 2:
rng = np.random.default_rng(seed=42)
NUM_KNAPSACKS = 10
NUM_ITEMS = 100
NUM_DIMENSIONS = 10
VALUES = rng.integers(0, 1000, size=NUM_ITEMS)
WEIGHTS = rng.integers(0, 1000, size=(NUM_ITEMS, NUM_DIMENSIONS))
CONSTRAINTS = rng.integers(1000 * 2, 1000 * NUM_ITEMS // NUM_KNAPSACKS, size=NUM_DIMENSIONS)

# print_info(VALUES, WEIGHTS, CONSTRAINTS)

In [29]:
# Problem 3:
rng = np.random.default_rng(seed=42)
NUM_KNAPSACKS = 100
NUM_ITEMS = 5000
NUM_DIMENSIONS = 100
VALUES = rng.integers(0, 1000, size=NUM_ITEMS)
WEIGHTS = rng.integers(0, 1000, size=(NUM_ITEMS, NUM_DIMENSIONS))
CONSTRAINTS = rng.integers(1000 * 10, 1000 * 2 * NUM_ITEMS // NUM_KNAPSACKS, size=NUM_DIMENSIONS)

# print_info(VALUES, WEIGHTS, CONSTRAINTS)